name:                abstract-effects-test
version:             0.1.0.0
github:              "vitalibarozzi/abstract-effects-test"
license:             MIT
author:              "Joao Vitor Vitali Barozzi"
maintainer:          "vitalivitor@gmail.com"
copyright:           "2023 Joao Vitor Vitali Barozzi"

dependencies:
- base >= 4.7 && < 5
- text
- abstract-effects

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wno-redundant-constraints

library:
  source-dirs: src
